// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Panier_service.Data;

#nullable disable

namespace Panier_service.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Panier_service.Models.Panier", b =>
                {
                    b.Property<int>("Id_client")
                        .HasColumnType("int");

                    b.Property<int>("Id_produit")
                        .HasColumnType("int");

                    b.Property<double?>("Prix")
                        .HasColumnType("float");

                    b.Property<int>("Qunatite")
                        .HasColumnType("int");

                    b.HasKey("Id_client", "Id_produit");

                    b.ToTable("Panier");
                });
#pragma warning restore 612, 618
        }
    }
}
